### ISSUE TITLE
python code without license comment

### ISSUE THREAD

**Issue by moylop260** [edanpiro/l10n_pe_ruc#1]
This module is a good module.
We are working with your module and we will add your colaboration name and license in `__openerp__.py`and all header comment of python files.

``` python
 # -*- coding: utf-8 -*-
 ##
 #    Module Writen to OpenERP, Open Source Management Solution
 #
 #    Copyright (c) 2014 Vauxoo - http://www.vauxoo.com
 #    All Rights Reserved.
 #    info@vauxoo.com
 ##
 #    Coded by: Edgard Pimentel (pimentelrojas@gmail.com)
 ##
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU Affero General Public License as
 #    published by the Free Software Foundation, either version 3 of the
 #    License, or (at your option) any later version.
 #
 #    This program is distributed in the hope that it will be useful,
 #    but WITHOUT ANY WARRANTY; without even the implied warranty of
 #    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #    GNU Affero General Public License for more details.
 #
 #    You should have received a copy of the GNU Affero General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 #
```

Do you have a problem with this license?

**Comment by moylop260** [comment]
FYI we have a your code with changes here:
https://github.com/Vauxoo/odoo-peru/blob/8.0/l10n_pe_vat_sunat_validation/__openerp__.py#L29
https://github.com/Vauxoo/odoo-peru/blob/8.0/l10n_pe_vat_sunat_validation/model/res_partner.py#L9

If you don't have problem our add license to all files.
We can't change to other license that your chose in original code.

**Comment by edanpiro** [comment]
the module is wrong,  I did changes at branch 8.0 I did a copy based on https://github.com/alexcuellar/l10n_pe_ruc

**Comment by moylop260** [comment]
Ok, I got it
Thank you!
